apiVersion: v1
kind: Service
metadata:
    name: "mxlabs-db98"
    labels:
        app: "mxlabs-db98"
spec:
    type: LoadBalancer
    ports:
    - port: 28888
      targetPort: 28888
      protocol: TCP
      name: http
    selector:
        app: "mxlabs-db98"